#!/bin/bash

# Generate CSS for versioned fonts with hash
# Called after subset-font.sh

FONT_DIR="dist/assets"
CSS_OUTPUT="dist/fonts.css"

if [ ! -d "$FONT_DIR" ]; then
  echo "⚠️  Font directory not found at $FONT_DIR"
  exit 0
fi

echo "📝 Generating font-face CSS..."

cat > "$CSS_OUTPUT" << 'CSS'
/* Auto-generated font-face declarations */
/* Generated by generate-font-css.sh */

@font-face {
  font-family: 'NotoColorEmoji';
  src: local('Noto Color Emoji'),
       url('./assets/noto-color-emoji.woff2') format('woff2'),
       url('./assets/noto-color-emoji.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}
CSS

# Find versioned fonts and add to CSS
for font_file in "$FONT_DIR"/*.ttf; do
  if [ -f "$font_file" ]; then
    font_name=$(basename "$font_file" .ttf)
    
    # Extract font family from filename
    if [[ $font_name == *"noto-color-emoji"* ]]; then
      cat >> "$CSS_OUTPUT" << CSS

/* Versioned: $font_name */
@font-face {
  font-family: 'NotoColorEmojiVersioned';
  src: url('./assets/$font_name.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}
CSS
    fi
  fi
done

echo "✅ Font CSS generated at $CSS_OUTPUT"
